export const PRESETS = [
  {
    id: 'twitter',
    label: 'Twitter / X',
    icon: '𝕏',
    description: '1200×628 — perfect for link previews',
    viewportWidth: 1200,
    settings: {
      gradientId: 'night',
      gradientFrom: '#1a1a2e',
      gradientTo: '#16213e',
      gradientAngle: 135,
      backgroundType: 'gradient',
      paddingPreset: 'comfortable',
      paddingValue: 48,
      shadowSize: 'large',
      borderRadius: 12,
      imageScale: 0.85,
      frameType: 'browser-dark',
    },
  },
  {
    id: 'linkedin',
    label: 'LinkedIn',
    icon: 'in',
    description: '1200×627 — professional sharing',
    viewportWidth: 1200,
    settings: {
      gradientId: 'ocean',
      gradientFrom: '#06B6D4',
      gradientTo: '#3B82F6',
      gradientAngle: 135,
      backgroundType: 'gradient',
      paddingPreset: 'comfortable',
      paddingValue: 48,
      shadowSize: 'large',
      borderRadius: 12,
      imageScale: 0.85,
      frameType: 'browser-light',
    },
  },
  {
    id: 'producthunt',
    label: 'Product Hunt',
    icon: '🚀',
    description: 'Clean launch screenshot',
    viewportWidth: 1440,
    settings: {
      gradientId: 'sunset',
      gradientFrom: '#F59E0B',
      gradientTo: '#EF4444',
      gradientAngle: 135,
      backgroundType: 'gradient',
      paddingPreset: 'spacious',
      paddingValue: 80,
      shadowSize: 'floating',
      borderRadius: 16,
      imageScale: 0.82,
      frameType: 'browser-light',
    },
  },
  {
    id: 'presentation',
    label: 'Presentation',
    icon: '📊',
    description: '16:9 slide-ready image',
    viewportWidth: 1440,
    settings: {
      gradientId: 'indigo',
      gradientFrom: '#6366F1',
      gradientTo: '#8B5CF6',
      gradientAngle: 135,
      backgroundType: 'gradient',
      paddingPreset: 'spacious',
      paddingValue: 80,
      shadowSize: 'floating',
      borderRadius: 16,
      imageScale: 0.80,
      frameType: 'minimal',
    },
  },
  {
    id: 'blog',
    label: 'Blog / Docs',
    icon: '📝',
    description: 'Clean minimal screenshot',
    viewportWidth: 1280,
    settings: {
      gradientId: 'silver',
      gradientFrom: '#F8FAFC',
      gradientTo: '#E2E8F0',
      gradientAngle: 135,
      backgroundType: 'gradient',
      paddingPreset: 'comfortable',
      paddingValue: 48,
      shadowSize: 'medium',
      borderRadius: 10,
      imageScale: 0.9,
      frameType: 'minimal',
    },
  },
  {
    id: 'minimal',
    label: 'Minimal',
    icon: '◻',
    description: 'No frame, transparent bg option',
    viewportWidth: 1440,
    settings: {
      backgroundType: 'transparent',
      paddingPreset: 'tight',
      paddingValue: 16,
      shadowSize: 'soft',
      borderRadius: 8,
      imageScale: 1,
      frameType: 'none',
    },
  },
]
